# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: hieuso
      MYSQL_USER: admin
      MYSQL_PASSWORD: hieuso
    
    # (this is just an example, not intended to be a production configuration)